--- 
project_name: PluginFactory
project_homepage: http://deveiate.org/projects/PluginFactory/
project_summary: A mixin for making plugin classes
project_description: |-
  PluginFactory is a mixin module that turns an including class into a factory for
  its derivatives, capable of searching for and loading them by name. This is
  useful when you have an abstract base class which defines an interface and basic
  functionality for a part of a larger system, and a collection of subclasses
  which implement the interface for different underlying functionality.
project_pubhost: deveiate
project_pubdir: /usr/local/www/public/code
project_licenses: 
- BSD
gem_pubhost: rubygems.org
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
release_smtphost: mail.faeriemud.org
post_install_message: ""
authors: 
  Martin Chase: stillflame@FaerieMUD.org
  Michael Granger: ged@FaerieMUD.org
project_dependencies: {}

dev_dependencies: {}

project_requirements: {}

additional_pkgfiles: []

excluded_pkgfiles: []

required_ruby_version: ">=1.8.7"
version_file: pluginfactory.rb
